"""Turn a scan into a concrete, reviewable list of moves.

The planner is pure: it reads a ScanReport and produces intents. It never
touches the disk. That is what makes dry-run trustworthy - the preview you
see is generated by the same code path that executes, so the preview cannot
drift from reality.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from .rules import CATEGORIES, MOVERABLE, PROTECTED
from .scanner import ScanReport

# Windows forbids these in filenames. We only ever append a suffix to an
# existing name, but the check guards against a source name we cannot
# re-create on a cross-platform copy.
_WIN_RESERVED = re.compile(r'[<>:"|?*]')


@dataclass
class MoveIntent:
    src: Path
    dst: Path
    category: str
    size: int


@dataclass
class SkipIntent:
    path: Path
    reason: str


@dataclass
class Plan:
    moves: list[MoveIntent] = field(default_factory=list)
    skips: list[SkipIntent] = field(default_factory=list)
    applied: bool = False

    @property
    def total_bytes(self) -> int:
        return sum(m.size for m in self.moves)

    def summary(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for m in self.moves:
            counts[m.category] = counts.get(m.category, 0) + 1
        return dict(sorted(counts.items()))


def unique_destination(dst: Path, taken: set[Path]) -> Path:
    """Return a destination that does not exist and was not already claimed.

    Never overwrites. ``report.pdf`` becomes ``report (1).pdf`` if a file of
    that name is already in the target folder.

    Windows names are case-insensitive, so the "already exists" probe has to
    be too - ``Report.pdf`` and ``report.pdf`` are the same file there. We
    key ``taken`` case-folded and probe with a case-insensitive listing.
    """
    if not _exists_ci(dst) and _key(dst) not in taken:
        taken.add(_key(dst))
        return dst

    stem, suffix = dst.stem, dst.suffix
    for n in range(1, 10_000):
        candidate = dst.with_name(f"{stem} ({n}){suffix}")
        if not _exists_ci(candidate) and _key(candidate) not in taken:
            taken.add(_key(candidate))
            return candidate

    raise RuntimeError(f"could not find a free name near {dst}")


def _key(path: Path) -> str:
    return str(path).lower()


def _exists_ci(path: Path) -> bool:
    """Existence check that respects Windows case-insensitivity.

    Falls back to a case-insensitive scan of the parent directory, so a
    differently-cased existing file is still detected as a conflict on
    Windows while staying a non-conflict on Linux.
    """
    if path.exists():
        return True
    parent = path.parent
    if not parent.is_dir():
        return False
    target = path.name.lower()
    try:
        for child in parent.iterdir():
            if child.name.lower() == target:
                return True
    except (OSError, PermissionError):
        return False
    return False


def build_plan(
    report: ScanReport,
    root: Path,
    *,
    include_protected: bool = False,
) -> Plan:
    """Build a move plan from a scan report.

    Args:
        report: the output of scanner.scan().
        root: the folder the scan was rooted at; destinations are created
            beneath it so nothing ever escapes the authorised folder.
        include_protected: opt in to moving PROTECTED files. Default False,
            which is what keeps the tool conservative.

    Returns:
        A Plan of move intents plus skips with reasons.
    """
    plan = Plan()
    root = Path(root).expanduser().resolve()
    taken: set[Path] = set()

    # Resolve the root's children once, not once per file.
    #
    # _is_inside() calls Path.resolve(), which on Windows issues a syscall per
    # path component. Doing that for every file cost 3.8s of the 7.5s total on
    # a 10,000-file scan. The destinations are always root/<category>, so the
    # set of directories that need checking is known up front.
    _validate_category_dirs(root)

    for entry in report.entries:
        category = entry.category

        if category == PROTECTED and not include_protected:
            plan.skips.append(
                SkipIntent(entry.path, "unclassified - left in place (use --include-protected to move)")
            )
            continue

        if category != PROTECTED and category not in MOVERABLE:
            # Defensive: rules.py should make this unreachable, but an
            # unknown category must never become an arbitrary destination.
            plan.skips.append(SkipIntent(entry.path, "unknown category"))
            continue

        target_dir = root / category

        # The containment guarantee is established once for all categories by
        # _validate_category_dirs() above, so it is not re-checked per file.
        # That check costs a filesystem syscall per path component and was
        # measurably the slowest part of planning a large scan.

        try:
            dst = unique_destination(target_dir / entry.path.name, taken)
        except RuntimeError as exc:
            plan.skips.append(SkipIntent(entry.path, str(exc)))
            continue

        if dst == entry.path:
            plan.skips.append(SkipIntent(entry.path, "already in place"))
            continue

        plan.moves.append(
            MoveIntent(src=entry.path, dst=dst, category=category, size=entry.size)
        )

    return plan


def _is_inside(child: Path, parent: Path) -> bool:
    try:
        child.resolve().relative_to(parent.resolve())
        return True
    except (ValueError, OSError):
        return False


def _validate_category_dirs(root: Path) -> None:
    """Reject any category name that would place a destination outside root.

    Checked once per category instead of once per file. The destinations in
    build_plan are always ``root / category / filename``, so if the category
    directory itself is inside the root, every file derived from it is too.

    Raises ValueError if a category is unsafe, which fails loudly at plan time
    rather than silently at move time.
    """
    for category in (*CATEGORIES, PROTECTED):
        target = root / category
        if not _is_inside(target, root):
            raise ValueError(
                f"category {category!r} resolves outside the target folder; "
                f"refusing to build a plan"
            )